"""Generate the offline province/city coordinates from QWeather's public location list.

Only geographic facts (city name, province and coordinates) are retained.
Usage: python scripts/update-weather-cities.py [downloaded-csv]
"""
import csv
import hashlib
import io
import json
import sys
import urllib.request
from pathlib import Path

URL = 'https://raw.githubusercontent.com/qwd/LocationList/master/China-City-List-latest.csv'
root = Path(__file__).resolve().parent.parent
data = Path(sys.argv[1]).read_bytes() if len(sys.argv) > 1 else urllib.request.urlopen(URL, timeout=30).read()
text = data.decode('utf-8-sig').replace('\r\r\n', '\n')
lines = text.splitlines()
rows = list(csv.DictReader(io.StringIO('\n'.join(lines[1:]))))
groups = {}
for row in rows:
    key = (row['Adm1_Name_ZH'], row['Adm2_Name_ZH'])
    groups.setdefault(key, []).append(row)

def normalize(name):
    return name.removesuffix('市').removesuffix('地区').removesuffix('自治州').removesuffix('特别行政区')

cities = []
for (province, city), group in groups.items():
    # Prefer the named city/administrative seat rather than an arbitrary district.
    best = next((r for r in group if normalize(r['Location_Name_ZH']) == normalize(city)), None)
    if best is None:
        best = next((r for r in group if r['AD_code'].endswith('00')), group[0])
    cities.append((best['Location_ID'], province, city, float(best['Latitude']), float(best['Longitude'])))
cities.sort(key=lambda c: c[0])
quote = lambda s: json.dumps(s, ensure_ascii=False)
out = ["import { WeatherCity } from './WeatherData';", '',
       '// Geographic facts extracted from QWeather LocationList; see doc/weather.md.',
       '// Generated by scripts/update-weather-cities.py. Source: ' + lines[0].split(',')[0],
       '// Source SHA-256: ' + hashlib.sha256(data).hexdigest(),
       'export const WEATHER_CITIES: WeatherCity[] = [']
for ident, province, city, lat, lon in cities:
    out.append(f'  new WeatherCity({quote(ident)}, {quote(province)}, {quote(city)}, {lat}, {lon}),')
out += ['];', '',
        'export const WEATHER_PROVINCES: string[] = [];',
        'WEATHER_CITIES.forEach((city: WeatherCity) => {',
        '  if (!WEATHER_PROVINCES.includes(city.province)) { WEATHER_PROVINCES.push(city.province); }',
        '});', '',
        'export function citiesInProvince(province: string): WeatherCity[] {',
        '  return WEATHER_CITIES.filter((city: WeatherCity) => city.province === province);',
        '}', '',
        'export function findWeatherCity(id: string): WeatherCity {',
        "  return WEATHER_CITIES.find((city: WeatherCity) => city.id === id) ||",
        "    WEATHER_CITIES.find((city: WeatherCity) => city.name === '广州市') || WEATHER_CITIES[0];",
        '}', '']
(root / 'entry/src/main/ets/model/WeatherCities.ets').write_text('\n'.join(out), encoding='utf-8')
print(f'Generated {len(set(c[1] for c in cities))} provinces, {len(cities)} cities/administrative areas.')
